version: "3"

volumes:
  notificator.mq:
    external: true

services:
  rabbitmq:
    container_name: notificator.mq
    image: rabbitmq:latest
    command: rabbitmq-server
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - notificator.mq:/var/lib/rabbitmq/data
