version: "3"

volumes:
  notificator.db:
    external: true

services:
  database:
    container_name: notificator.db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - notificator.db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234
